### PR TITLE
Catching IOError while handling pyramid error

### PR DESCRIPTION
**Pull request by marcofalcioni**
IOErrors are common when the client disconnects. This change
allows us to gather better exception information.

### CODE REVIEW

**Comment by marcofalcioni** [comment]
@mmerickel are you still watching this project?

**Comment by bertjwregeer** [comment]
Wait a minute... why are we including the `.idea` folder?

**Comment by tseaver** [comment]
@marcofalcioni Please get rid of all of 2e57aa2 except for the changelog parts;

```bash
$ git rm -rf .idea/
$ git commit --amend -a
```

**Comment by tseaver** [comment]
@marcofalcioni The other option would be to rebase your branch (rather than merging it) against the upstream master.

**Comment by tseaver** [comment]
@marcofalcioni this would be **much** simpler if you could rebase your branch to incldee only the first three commits:  the rest are just SCARY mess at this point.

**Pull request closed without merging**
